FROM resin/%%RESIN_MACHINE_NAME%%-systemd

RUN apt-get update \
	&& apt-get install -y ruby \
	# Remove package lists to free up space 
	&& rm -rf /var/lib/apt/lists/*

#switch on systemd init system in container
ENV INITSYSTEM on

COPY . /usr/src/app
WORKDIR /usr/src/app

CMD ["ruby", "helloworld.rb"]
 
