FROM resin/%%RESIN_MACHINE_NAME%%-debian

RUN apt-get update && apt-get install -yq --no-install-recommends \
    ruby && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

#switch on systemd init system in container
ENV INITSYSTEM on

COPY . /usr/src/app
WORKDIR /usr/src/app

CMD ["ruby", "helloworld.rb"]
 
